### ISSUE TITLE
Release new gem version

### ISSUE THREAD

**Issue by alno** [aasmith/feed-normalizer#1]
Current gem version is two years old, and there were some improvements for this time.

Maybe, it's possible to release it?

**Comment by nertzy** [comment]
I agree! In my own project I ended up rolling my own version of the gem from source.

**Comment by aasmith** [comment]
Release party!  Pushed 1.5.2 to gemcutter.

**Comment by nertzy** [comment]
Yeah! I'll bring the soda. :)
